export const grupos = [
  {
    idGrupo: 1,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero A",
  },
  {
    idGrupo: 2,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero B",
  },
  {
    idGrupo: 3,
    curso: "Segundo",
    anioAcademico: "2020-2021",
    nombreGrupo: "Segundo A",
  },
  {
    idGrupo: 4,
    curso: "Segundo",
    anioAcademico: "2020-2021",
    nombreGrupo: "Segundo B",
  },
  {
    idGrupo: 5,
    curso: "Tercero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Tercero A",
  },
  {
    idGrupo: 6,
    curso: "Tercero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Tercero B",
  },
];

export const alumnos = [
  {
    idAlumno: 1,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idGrupo: 1,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero A",
  },
  {
    idAlumno: 2,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idGrupo: 1,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero A",
  },
  {
    idAlumno: 3,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idGrupo: 1,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero A",
  },
  {
    idAlumno: 4,
    nombreAlumno: "Antonio",
    apellidosAlumno: "enero Febrero",
    idGrupo: 2,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero B",
  },
  {
    idAlumno: 5,
    nombreAlumno: "Monica",
    apellidosAlumno: "Miercoles Jueves",
    idGrupo: 2,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero B",
  },
  {
    idAlumno: 6,
    nombreAlumno: "Rafael",
    apellidosAlumno: "Junio Maiercoles",
    idGrupo: 3,
    curso: "Segundo",
    anioAcademico: "2020-2021",
    nombreGrupo: "Segundo A",
  },
  {
    idAlumno: 7,
    nombreAlumno: "Pepito",
    apellidosAlumno: "Piedra MAroto",
    idGrupo: 3,
    curso: "Segundo",
    anioAcademico: "2020-2021",
    nombreGrupo: "Segundo A",
  },
  {
    idAlumno: 8,
    nombreAlumno: "Jacinto",
    apellidosAlumno: "Alas Negras",
    idGrupo: 3,
    curso: "Segundo",
    anioAcademico: "2020-2021",
    nombreGrupo: "Segundo A",
  },
  {
    idAlumno: 9,
    nombreAlumno: "Gloria",
    apellidosAlumno: "Armas Pocas",
    idGrupo: 4,
    curso: "Segundo",
    anioAcademico: "2020-2021",
    nombreGrupo: "Segundo B",
  },
  {
    idAlumno: 10,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Todos Aqui",
    idGrupo: 4,
    curso: "Segundo",
    anioAcademico: "2020-2021",
    nombreGrupo: "Segundo B",
  },
  {
    idAlumno: 11,
    nombreAlumno: "Javier",
    apellidosAlumno: "Estoy Cansado",
    idGrupo: 4,
    curso: "Segundo",
    anioAcademico: "2020-2021",
    nombreGrupo: "Segundo B",
  },
  {
    idAlumno: 12,
    nombreAlumno: "Carlos",
    apellidosAlumno: "Canarias Bonito",
    idGrupo: 5,
    curso: "Tercero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Tercero A",
  },
  {
    idAlumno: 13,
    nombreAlumno: "Gema",
    apellidosAlumno: "Cuervo Volando",
    idGrupo: 5,
    curso: "Tercero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Tercero A",
  },
  {
    idAlumno: 14,
    nombreAlumno: "Casemiro",
    apellidosAlumno: "Juega Madrid",
    idGrupo: 5,
    curso: "Tercero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Tercero A",
  },
  {
    idAlumno: 15,
    nombreAlumno: "Macarena",
    apellidosAlumno: "Sevilla Jaen",
    idGrupo: 6,
    curso: "Tercero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Tercero B",
  },
  {
    idAlumno: 16,
    nombreAlumno: "Anastasio",
    apellidosAlumno: "Nombre Raro",
    idGrupo: 6,
    curso: "Tercero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Tercero B",
  },
  {
    idAlumno: 17,
    nombreAlumno: "Lucila",
    apellidosAlumno: "Mesa Silla",
    idGrupo: 6,
    curso: "Tercero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Tercero B",
  },
];

export const trimestres = [
  {
    idTrimestre: 0,
    nombreTrimestre: "Primer Trimestre",
  },
  {
    idTrimestre: 1,
    nombreTrimestre: "Segundo Trimestre",
  },
  {
    idTrimestre: 2,
    nombreTrimestre: "Tercer Trimestre",
  },
];

export const parciales = [
  {
    idParcial: 0,
    nombreParcial: "Parcial 1",
    pesoParcial: 25,
  },
  {
    idParcial: 1,
    nombreParcial: "Parcial 2",
    pesoParcial: 25,
  },
  {
    idParcial: 2,
    nombreParcial: "Parcial 5",
    pesoParcial: 50,
  },
];

export const realiza = [
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 0,
    idTrimestre: 0,
    nota: 8,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 0,
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 0,
    idTrimestre: 0,
    nota: 9,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 1,
    idTrimestre: 0,
    nota: 5,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 1,
    idTrimestre: 0,
    nota: 7,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 0,
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 2,
    idTrimestre: 0,
    nota: 8,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 2,
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 2,
    idTrimestre: 0,
    nota: 9,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 4,
    idTrimestre: 0,
    nota: 4,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 4,
    idTrimestre: 0,
    nota: 3,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 4,
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 5,
    nombreAlumno: "Rafael",
    apellidosAlumno: "Junio Maiercoles",
    idParcial: 4,
    idTrimestre: 0,
    nota: 3,
  },
  {
    idAlumno: 6,
    nombreAlumno: "Pepito",
    apellidosAlumno: "Piedra MAroto",
    idParcial: 4,
    idTrimestre: 0,
    nota: 3,
  },
  {
    idAlumno: 7,
    nombreAlumno: "Jacinto",
    apellidosAlumno: "Alas Negras",
    idParcial: 4,
    idTrimestre: 0,
    nota: 3,
  },
  {
    idAlumno: 5,
    nombreAlumno: "Rafael",
    apellidosAlumno: "Junio Maiercoles",
    idParcial: 0,
    idTrimestre: 0,
    nota: 10,
  },
  {
    idAlumno: 6,
    nombreAlumno: "Pepito",
    apellidosAlumno: "Piedra MAroto",
    idParcial: 0,
    idTrimestre: 0,
    nota: 8,
  },
  {
    idAlumno: 7,
    nombreAlumno: "Jacinto",
    apellidosAlumno: "Alas Negras",
    idParcial: 0,
    idTrimestre: 0,
    nota: 7,
  },
  {
    idAlumno: 5,
    nombreAlumno: "Rafael",
    apellidosAlumno: "Junio Maiercoles",
    idParcial: 1,
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 6,
    nombreAlumno: "Pepito",
    apellidosAlumno: "Piedra MAroto",
    idParcial: 1,
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 7,
    nombreAlumno: "Jacinto",
    apellidosAlumno: "Alas Negras",
    idParcial: 1,
    idTrimestre: 0,
    nota: 4,
  },
];

export const notaFinal = [
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 3,
    nombreAlumno: "Antonio",
    apellidosAlumno: "enero Febrero",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 4,
    nombreAlumno: "Monica",
    apellidosAlumno: "Miercoles Jueves",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 5,
    nombreAlumno: "Rafael",
    apellidosAlumno: "Junio Maiercoles",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 6,
    nombreAlumno: "Pepito",
    apellidosAlumno: "Piedra MAroto",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 7,
    nombreAlumno: "Jacinto",
    apellidosAlumno: "Alas Negras",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 8,
    nombreAlumno: "Gloria",
    apellidosAlumno: "Armas Pocas",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 9,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Todos Aqui",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 10,
    nombreAlumno: "Javier",
    apellidosAlumno: "Estoy Cansado",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 11,
    nombreAlumno: "Carlos",
    apellidosAlumno: "Canarias Bonito",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 12,
    nombreAlumno: "Gema",
    apellidosAlumno: "Cuervo Volando",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 13,
    nombreAlumno: "Casemiro",
    apellidosAlumno: "Juega Madrid",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 14,
    nombreAlumno: "Macarena",
    apellidosAlumno: "Sevilla Jaen",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 15,
    nombreAlumno: "Anastasio",
    apellidosAlumno: "Nombre Raro",
    idTrimestre: 0,
    notaFinal: 0,
  },
  {
    idAlumno: 16,
    nombreAlumno: "Lucila",
    apellidosAlumno: "Mesa Silla",
    idTrimestre: 0,
    notaFinal: 0,
  },
];

export const alumnosGrupo1 = [
  {
    idAlumno: 1,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idGrupo: 1,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero A",
  },
  {
    idAlumno: 2,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idGrupo: 1,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero A",
  },
  {
    idAlumno: 3,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idGrupo: 1,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero A",
  },
];

export const alumnosGRupo2 = [
  {
    idAlumno: 4,
    nombreAlumno: "Antonio",
    apellidosAlumno: "enero Febrero",
    idGrupo: 2,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero B",
  },
  {
    idAlumno: 5,
    nombreAlumno: "Monica",
    apellidosAlumno: "Miercoles Jueves",
    idGrupo: 2,
    curso: "Primero",
    anioAcademico: "2020-2021",
    nombreGrupo: "Primero B",
  },
];

export const realizaAlumno1Trimestre1 = [
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 0,
    idTrimestre: 0,
    nota: 8,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 1,
    idTrimestre: 0,
    nota: 4,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 2,
    idTrimestre: 0,
    nota: 6,
  },
];

export const realizaAlumno2Trimestre1 = [
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 0,
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 1,
    idTrimestre: 0,
    nota: 5,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 2,
    idTrimestre: 0,
    nota: 8,
  },
];

export const realizaAlumno3Trimestre1 = [
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 0,
    idTrimestre: 0,
    nota: 9,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 1,
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 2,
    idTrimestre: 0,
    nota: 8,
  },
];

export const realizaGrupo0Trimestre1 = [
  //tambien pido el nobre del parcial para la cabecera
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 0,
    nombreParcial: "Parcial 1",
    idTrimestre: 0,
    nota: 8,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 1,
    nombreParcial: "Parcial 2",
    idTrimestre: 0,
    nota: 4,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 2,
    nombreParcial: "Parcial 3",
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 0,
    nombreParcial: "Parcial 1",
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 1,
    nombreParcial: "Parcial 2",
    idTrimestre: 0,
    nota: 5,
  },
  {
    idAlumno: 1,
    nombreAlumno: "Ana",
    apellidosAlumno: "De-las-tejas Verdes",
    idParcial: 2,
    nombreParcial: "Parcial 3",
    idTrimestre: 0,
    nota: 8,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 0,
    nombreParcial: "Parcial 1",
    idTrimestre: 0,
    nota: 9,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 1,
    nombreParcial: "Parcial 2",
    idTrimestre: 0,
    nota: 6,
  },
  {
    idAlumno: 2,
    nombreAlumno: "Luisa",
    apellidosAlumno: "Fernanda Manuela",
    idParcial: 2,
    nombreParcial: "Parcial 3",
    idTrimestre: 0,
    nota: 8,
  },
];
export const realizaAlumno1Grupo0Trimestre1 = [
  //tambien pido el nobre del parcial para la cabecera
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 0,
    nombreParcial: "Parcial 1",
    idTrimestre: 0,
    nota: 8,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 1,
    nombreParcial: "Parcial 2",
    idTrimestre: 0,
    nota: 4,
  },
  {
    idAlumno: 0,
    nombreAlumno: "Felipe",
    apellidosAlumno: "Lunes Martes",
    idParcial: 2,
    nombreParcial: "Parcial 5",
    idTrimestre: 0,
    nota: 6,
  },
];

export const parcialesGrupo0Trimestre1 = [
  {
    idParcial: 0,
    nombreParcial: "Parcial 1",
  },
  {
    idParcial: 1,
    nombreParcial: "Parcial 2",
  },
  {
    idParcial: 2,
    nombreParcial: "Parcial 3",
  },
];
